### ISSUE TITLE
Display information about route

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#5] opened 2017-07-14 08:00 UTC
It could be nice to have more information by clicking on a route.

**Comment by ArnaudWeyts** [comment] 2017-07-21 17:19
duplicate of #11

**Comment by jbelien** [comment] 2017-07-21 19:58
No no, it is not a duplicate of #11 !
My idea was to add a function to have more information about the cycling network (not the route calculated).

**Comment by ArnaudWeyts** [comment] 2017-07-21 20:24
Oh okay, my bad. Maybe a good idea to sum up what kind of information that would be.

**Closed as completed** 2018-12-04 15:15 UTC
Labels: enhancement, backlog
